### ISSUE TITLE
Nested contexts

### ISSUE THREAD

**Issue by MaximumViciousDeer** [inconspicuous-creations/Inconspicuous.Framework#3]
I am making a spaceship game which currently doesn't use DI, but I have read about this framework and would like to use it. Some basic info about my game:
- Each player has one ship.
- Ships can be docked inside bigger ships.
- Local co-op support.

I was thinking about making each ship a context - that way I could inject ship configuration, player input etc. to the ship's submodules (which are sub transforms of the ship). The ship may be nested when docked.
This does however not seem to be entirely achievable using Inconspicuous.
How would you use Inconspicuous in this case?

**Comment by yuhe00** [comment]
You are right, and it's intentional. Contexts and sub-contexts are only responsible for object construction and can not be reconfigured once they are initialized.

My advice is to try to use as much of your existing code as possible, and refactor it into separate injectable services/models/viewmodels in a way that makes sense, e.g. a ShipViewModel that has a property that changes when it's docked, etc.

Inconspicuous.Framework should not dictate how you structure your code. You don't want to tie your game logic to a third-party library!

**Comment by MaximumViciousDeer** [comment]
I'll keep that in mind. Still using a DI framework will probably dictate your code structure to some extent. Inconspicuous also seems a bit different from other Unity DI frameworks so if using it I will be tied to a certain architecture.
